name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale: # Vale linting job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can access all commits

    - name: Install Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
           **/*.md

    - name: List all changed markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Run Vale on changed files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        mkdir -p vale_output
        echo "Running Vale on changed files:"
        for file in $ALL_CHANGED_FILES; do
          echo "Running Vale on $file"
          ./vale --output=JSON $file > "vale_output/vale_output_${file//\//_}.json"
        done
        echo "Vale outputs:"
        ls -l vale_output
  
    - name: Merge JSON outputs
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: jq -s '.' vale_output/vale_output_*.json > vale_report.json

    - name: Suggest changes
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: vale
        level: warning
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reviewdog_flags: "--jsonc < vale_report.json"
